version: '3.9'

services:
  vetapp:
    image: vetapp:0.0.1
    deploy:
      mode: replicated
      replicas: 3
    ports:
      - "9090-9092:8090"
    environment:
      DB_URL: "jdbc:h2:tcp://h2db/vetapp-db;DB_CLOSE_DELAY=-1"
      DB_USERNAME: "test"
      DB_PASSWORD: "1234"
      JWT_KEY: "jwtProject"
      JWT_ISSUER: "mstech"
      JWT_EXPIRE: 15

  h2db:
    image: build/h2database
    ports:
      - "9092:8082"